name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Install ARM development tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi libc6-dev-armel-cross

    - name: Install dependencies
      run: |
        go get github.com/alivanz/go-simd/arm
        go mod tidy

    - name: Build
      env:
        CC: arm-linux-gnueabi-gcc
        GOARCH: arm
        CGO_ENABLED: 1
      run: go build -v ./...

    - name: Test
      env:
        CC: arm-linux-gnueabi-gcc
        GOARCH: arm
        CGO_ENABLED: 1
      run: go test -v ./...

  status-check:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Check test job status
      if: needs.test.result != 'success'
      run: exit 1

    - name: Status Check
      if: needs.test.result == 'success'
      run: echo "All tests passed successfully!"